# Generated by Django 5.2.6 on 2025-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
